evaluate-commands %sh{
    config_files="
        common.kak
        commands.kak
        beacon.kak
        tmux.kak
        languages.kak
        plugins.kak
        go-decls.kak
    "

    for file in $config_files; do
        printf "%s\n" "
        try %{
            source \"%val{config}/$file\"
        } catch %{
            echo -debug %val{error}
        }"
    done
}

