evaluate-commands %sh{
    config_files="
        commands.kak
        common.kak
        languages.kak
        plugins.kak
        go-decls.kak
    "

    for file in $config_files; do
        printf "%s" "
            try %{
                source %{$kak_config/$file}
            } catch %{
                echo -debug %val{error}
            }
        "
    done
}
