# https://github.com/jesseduffield/lazygit/issues/802
gui:
    # stuff relating to the UI
  scrollHeight: 2 # how many lines you scroll by
  scrollPastBottom: true # enable scrolling past the bottom
  sidePanelWidth: 0.3333 # number from 0 to 1
  theme:
    lightTheme: true # For terminals with a light background
    activeBorderColor:
      - magenta
      - bold
    inactiveBorderColor:
      - black
    optionsTextColor:
      - blue
    selectedLineBgColor:
      - white
  commitLength:
    show: true
  mouseEvents: true
  skipUnstageLineWarning: false
  skipStashWarning: true
reporting: "off"
startuppopupversion: 1
